"""
Qwen3-Embedding (text-embedding-v4) feature generation script
=============================================================
This script generates LLM-based text embeddings for drug representations 
using the DashScope TextEmbedding API provided by Alibaba Cloud (Tongyi Lab).

Model information:
- Model name: text-embedding-v4
- Series: Qwen3-Embedding (based on Qwen3 Large Language Model)
- Architecture: Transformer-based LLM; embeddings derived from [EOS] hidden state
- API documentation: https://bailian.console.aliyun.com/?spm=5176.29619931.J_SEsSjsNv72yRuRFS2VknO.2.74cd405f9CZmiL&tab=api#/api/?type=model&url=2712515
- Reference: Zhang et al., 2025, *Qwen3-Embedding: Advancing Text Embedding and Reranking Through Foundation Models*
- SDK requirement: dashscope >= 1.14.0

Output:
- A JSON file storing the embeddings of drug textual descriptions (IUPAC names).
- Used in the second-stage representation of the LKE-DTA model.
"""

import json
from http import HTTPStatus
import dashscope  # Alibaba Cloud SDK for accessing Qwen models

# ===========================
# Function: get_embedding()
# ===========================
# This function sends a text query (drug description) to the Qwen3-Embedding model
# through the DashScope API and returns its embedding vector.
# The embeddings are generated by the Qwen3 LLM backbone (text-embedding-v4),
# corresponding to the last-layer hidden state of the [EOS] token.
def get_embedding(input_text):
    response = dashscope.TextEmbedding.call(
        model=dashscope.TextEmbedding.Models.text_embedding_v4,  # Qwen3-Embedding model
        input=input_text
    )
    if response.status_code == HTTPStatus.OK:
        return response.output['embeddings'][0]['embedding']
    else:
        print(f"Error: {response.status_code}")
        return None


# ===========================
# Step 1: Load drug descriptions
# ===========================
# The input file (IUPAC_name.json) contains textual drug names/descriptions.
# Each entry is passed to the Qwen3-Embedding API to obtain a high-dimensional
# semantic representation vector.
with open('data/IUPAC_name.json', 'r') as f:
    drug_descriptions = json.load(f)

# ===========================
# Step 2: Generate embeddings
# ===========================
all_embedding = {}
for idx, drug_name in enumerate(drug_descriptions):
    embedding = get_embedding(drug_descriptions[drug_name])
    if embedding is not None:
        all_embedding[drug_name] = embedding
        print(f"[{idx+1}] Embedded: {drug_name}")
    else:
        print(f"[{idx+1}] Failed: {drug_name}")

# ===========================
# Step 3: Save output
# ===========================
# Save all generated embeddings in JSON format for reproducibility.
# This file is later used for drug representation in the LKE-DTA pipeline.
output_path = 'data/Qwen3_v4_representation.json'
with open(output_path, 'w') as f:
    json.dump(all_embedding, f, indent=4)

print(f"✅ Embeddings saved to: {output_path}")
